- name: create the ec2 instance
  hosts: localhost
  become: yes

  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-0d45d6251e7b55a6a
    zone_id: Z04726272EU5J4JM1J4UL
    domain_name: daws86.icu
    region: us-est-1

    instances:
      - redis
      - mysql

  tasks:

    # creating the ec2 instances
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    # creating the route53 records
    - name: create route53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"

    - name: create route53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
      when: item.item == "frontend"
      loop: "{{ ec2_output.results }}"