[mongodb]
mongodb.daws86.icu

[redis]
redis.daws86.icu

[mysql]
mysql.daws86.icu

[catalogue]
catalogue.daws86.icu


[frontend]
frontend.daws86.icu

[local]
localhost


[all:vars]
anisble_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
